---
#install nginx
- name: install nginx
  apt: name=nginx state=present
  notify:
    - restart nginx

# Setup PHP on System
- name: Install python-properties
  apt: name=python-software-properties state=present

# Adding PHP repository
- name: Add PHP Repository
  apt_repository: repo='ppa:ondrej/php'

# Updating cache
- name: Update apt cache if repository just added.
  apt: update_cache=yes

# Installing PHP
- name: PHP | install php packages
  apt: pkg={{ item }} state=installed
  with_items:
  - "php{{ php_version }}"
  - "php{{ php_version }}-fpm"
  - "php{{ php_version }}-cli"
  - "php{{ php_version }}-common"
  - "php{{ php_version }}-curl"
  - "php{{ php_version }}-json"
  - "php{{ php_version }}-gd"
  - "php{{ php_version }}-mcrypt"
  - "php{{ php_version }}-odbc"
  - "php{{ php_version }}-mbstring"
  - "php{{ php_version }}-mysql"
  - "php{{ php_version }}-xmlrpc"
  - "php{{ php_version }}-opcache"
  - "php{{ php_version }}-intl"
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-xml"
  - "libapache2-mod-php{{ php_version }}"
  notify: 
    - restart php
