---
- name: Download drupal archive file
  get_url:
    url: https://ftp.drupal.org/files/projects/drupal-8.4.2.tar.gz
    dest: /var/www

- name: make directory 
  file:
    path: /var/www/html/drupal
    state: directory
    mode: 0755
    owner: www-data
    group: www-data

- name: unzip download file
  unarchive: src=/var/www/drupal-8.4.2.tar.gz  dest=/var/www/html/drupal remote_src=yes

- name: configure Nginx Drupal Site
  copy: 
    src: /var/www/html/drupal 
    dest: /etc/nginx/sites-available/drupal

- name: enable the drupal site
  file:
    src: /etc/nginx/sites-available/drupal
    dest: /etc/nginx/sites-enabled/
    state: link

- name: restart nginx
  service:
    name: nginx
    state: restarted
